name: flutter_web_data_table
description: A DataTable for Flutter Web that is implemented a sorting, text filtering and selecting.
version: 0.0.2
homepage: https://github.com/keyber-inc/flutter_web_data_table

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
